<?php

namespace app\controllers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-17 at 04:40:11.
 */
class PayControllerTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var PayController
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $_SERVER['HTTP_HOST'] = 'atc58.bit';
    $_SERVER['REQUEST_URI'] = 'index.php?r=pay/check';
    $this->object = new PayController;
    $this->object->init();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @covers app\controllers\PayController::actions
   * @todo   Implement testActions().
   */
  public function testActions() {
    $this->object->runAction('check');
  }

}
